apiVersion: apps/v1        
kind: Deployment           
metadata:
  name: myapp-deployment    
  labels:
    app: myapp              
spec:
  replicas: 3              
  selector:
    matchLabels:
      app: myapp            
  template:
    metadata:
      labels:
        app: myapp          
    spec:
      containers:
      - name: myapp-container   
        image: yaeshvann/myimage  
        ports:
        - containerPort: 8080 
